version: "3.3"

services:
  backend:
    build: ./backend
    container_name: planningpoker_backend
    environment:
      - ENV=prod
      - PORT=80
    ports:
      - "${BACKEND_PORT}:80"
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=${BACKEND_URL}
    container_name: planningpoker_frontend
    ports:
      - "${FRONTEND_PORT}:80"
